In [1]:
!pip install /kaggle/input/pip-install-lifelines/autograd-1.7.0-py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/autograd-gamma-0.5.0.tar.gz
!pip install /kaggle/input/pip-install-lifelines/interface_meta-1.3.0-py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/formulaic-1.0.2-py3-none-any.whl
!pip install /kaggle/input/pip-install-lifelines/lifelines-0.30.0-py3-none-any.whl

Processing /kaggle/input/pip-install-lifelines/autograd-1.7.0-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from autograd==1.7.0) (1.26.4)
autograd is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Processing /kaggle/input/pip-install-lifelines/autograd-gamma-0.5.0.tar.gz
  Preparing metadata (setup.py) ... done
Requirement already satisfied: autograd>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from autograd-gamma==0.5.0) (1.7.0)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from autograd-gamma==0.5.0) (1.13.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from autograd>=1.2.0->autograd-gamma==0.5.0) (1.26.4)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4031 sha256=1d02c1f1580dcee2c46f4ef3e309db72e7403c4fb4bc7cc5bb8b14fe9ea8a875
  Stored in directory: /root/.cache/pip/wheels/6b/b5/e0/4c79e15c0b5f2c15ecf613c720bb20daab20a666eb67135155
Successfully built autograd-gamma
Installing collected packages: autograd-gamma
Successfully installed autograd-gamma-0.5.0
Processing /kaggle/input/pip-install-lifelines/interface_meta-1.3.0-py3-none-any.whl
Installing collected packages: interface-meta
Successfully installed interface-meta-1.3.0
Processing /kaggle/input/pip-install-lifelines/formulaic-1.0.2-py3-none-any.whl
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.3.0)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.26.4)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (2.1.4)
Requirement already satisfied: scipy>=1.6 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.13.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (4.12.2)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.10/dist-packages (from formulaic==1.0.2) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->formulaic==1.0.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->formulaic==1.0.2) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->formulaic==1.0.2) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0->formulaic==1.0.2) (1.16.0)
Installing collected packages: formulaic
Successfully installed formulaic-1.0.2
Processing /kaggle/input/pip-install-lifelines/lifelines-0.30.0-py3-none-any.whl
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.13.1)
Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (2.1.4)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (3.7.1)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.7.0)
Requirement already satisfied: autograd-gamma>=0.3 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (0.5.0)
Requirement already satisfied: formulaic>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from lifelines==0.30.0) (1.0.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic>=0.2.2->lifelines==0.30.0) (1.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from formulaic>=0.2.2->lifelines==0.30.0) (4.12.2)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.10/dist-packages (from formulaic>=0.2.2->lifelines==0.30.0) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0->lifelines==0.30.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.1->lifelines==0.30.0) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.1->lifelines==0.30.0) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines==0.30.0) (1.16.0)
Installing collected packages: lifelines
Successfully installed lifelines-0.30.0

In [2]:
import warnings
warnings.simplefilter(action='ignore')

import os
import requests
import joblib

import numpy
import pandas

import matplotlib.pyplot as plt
import scipy.stats as stats
import tensorflow_decision_forests as tfdf

In [3]:
from catboost import CatBoostRegressor ,Pool
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.linear_model import ElasticNetCV, LassoCV, RidgeCV
from sklearn.svm import SVR

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import AdaBoostRegressor

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import KFold, cross_val_score

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectFromModel

from sklearn.impute import SimpleImputer
import sklearn.linear_model as linear_model
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [4]:
train = pandas.read_csv('/kaggle/input/equity-post-HCT-survival-predictions/train.csv').drop(columns=['ID'])
test = pandas.read_csv('/kaggle/input/equity-post-HCT-survival-predictions/test.csv').drop(columns=['ID'])

In [5]:
from lifelines import KaplanMeierFitter

def calculate_survival_probabilities(df, time_col, event_col):
    kmf = KaplanMeierFitter()
    kmf.fit(df[time_col], df[event_col])
    return kmf.survival_function_at_times(df[time_col]).values

def preprocess_survival_data(df, time_col='efs_time', event_col='efs'):
    df['target'] = calculate_survival_probabilities(df, time_col, event_col)
    df.loc[df[event_col] == 0, 'target'] -= 0.2  # Adjust for censored data
    return df

train = preprocess_survival_data(train)

In [6]:
encoder = LabelEncoder()
normalize = SimpleImputer(strategy='mean')

In [7]:
for i in zip(train.columns,train.dtypes):
    if i[1]=='O':
        train[i[0]] = train[i[0]].fillna('Unknown')
        train[i[0]]=encoder.fit_transform(train[i[0]].to_numpy().reshape(-1,1))
    else:
        train[i[0]] = train[i[0]].fillna(0)
        #train[i[0]]=normalize.fit_transform(numpy.array(train[i[0]]).reshape(-1,1))
for i in zip(test.columns,test.dtypes):
    if i[1]=='O':
        test[i[0]] = test[i[0]].fillna('Unknown')
        test[i[0]]=encoder.fit_transform(test[i[0]].to_numpy().reshape(-1,1))
    else:
        test[i[0]] = test[i[0]].fillna(0)
        #test[i[0]]=normalize.fit_transform(numpy.array(test[i[0]]).reshape(-1,1))

In [8]:
train_x = train.drop(columns=['efs', 'efs_time', 'target'])
train_y = train['target']
    
#train.hist(figsize=(16, 20), bins=50, xlabelsize=8, ylabelsize=8)

#clf = GradientBoostingRegressor(n_estimators=100).fit(train_x, train_y)
#model = SelectFromModel(clf, prefit=True)

#weight = model.transform(train_x).reshape(-1)
train.head()

,dri_score,psych_disturb,cyto_score,diabetes,hla_match_c_high,hla_high_res_8,tbi_status,arrhythmia,hla_low_res_6,graft_type,...,donor_related,melphalan_dose,hla_low_res_8,cardiac,hla_match_drb1_high,pulm_moderate,hla_low_res_10,efs,efs_time,target
0,7,0,7,0,0.0,0.0,0,0,6.0,0,...,3,1,8.0,0,2.0,0,10.0,0.0,42.356,0.258687
1,2,0,1,0,2.0,8.0,6,0,6.0,1,...,1,1,8.0,0,2.0,3,10.0,1.0,4.672,0.847759
2,7,0,7,0,2.0,8.0,0,0,6.0,0,...,1,1,8.0,0,2.0,0,10.0,0.0,19.793,0.262424
3,0,0,1,0,2.0,8.0,0,0,6.0,0,...,3,1,8.0,0,2.0,0,10.0,0.0,102.349,0.256661
4,0,0,7,0,2.0,8.0,0,0,6.0,1,...,1,0,8.0,0,2.0,0,10.0,0.0,16.223,0.264674

In [9]:
Fold=5
kf = KFold(n_splits=Fold)

cat_pre_train = numpy.zeros(len(train))
cat_pre_test = numpy.zeros(len(test))

catboost = CatBoostRegressor(grow_policy='Depthwise',
                             iterations=1000,
                             eval_metric='RMSE',
                             random_state=0,
                             verbose=100)

for i, (train_index, test_index) in enumerate(kf.split(train)):

    print(f"FOLD: {i}")

    x_fold=train_x[train_index[0]: train_index[len(train_index)-1]]
    y_fold=train_y[train_index[0]: train_index[len(train_index)-1]]

    x_test_fold=train_x[test_index[0]: test_index[len(test_index)-1]]
    y_test_fold=train_y[test_index[0]: test_index[len(test_index)-1]]

    cat_features = list(train_x.select_dtypes(include=['object', 'category']).columns)
    
    train_pool = Pool(x_fold, y_fold, cat_features=cat_features)
    val_pool = Pool(x_test_fold, y_test_fold, cat_features=cat_features)
    
    #weight_ = weight[train_index[0]: train_index[len(train_index)-1]]
    
    catboost.fit(train_pool, eval_set=(val_pool), verbose=50, early_stopping_rounds=100)

    cat_pre_train+=catboost.predict(train_x)
    
cat_pre_test=catboost.predict(test)
print(catboost.score(x_test_fold, y_test_fold))

FOLD: 0
Learning rate set to 0.08333
0:	learn: 0.2582976	test: 0.2571838	best: 0.2571838 (0)	total: 82.2ms	remaining: 1m 22s
50:	learn: 0.2313168	test: 0.2359140	best: 0.2359140 (50)	total: 950ms	remaining: 17.7s
100:	learn: 0.2229820	test: 0.2334571	best: 0.2334571 (100)	total: 1.8s	remaining: 16s
150:	learn: 0.2131155	test: 0.2323119	best: 0.2323105 (149)	total: 2.69s	remaining: 15.1s
200:	learn: 0.2037304	test: 0.2323088	best: 0.2321023 (169)	total: 3.54s	remaining: 14.1s
250:	learn: 0.1961278	test: 0.2325969	best: 0.2321023 (169)	total: 4.32s	remaining: 12.9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.2321023054
bestIteration = 169

Shrink model to first 170 iterations.
FOLD: 1
Learning rate set to 0.086301
0:	learn: 0.2579931	test: 0.2581588	best: 0.2581588 (0)	total: 20.9ms	remaining: 20.9s
50:	learn: 0.2313967	test: 0.2328338	best: 0.2328338 (50)	total: 971ms	remaining: 18.1s
100:	learn: 0.2237409	test: 0.2249283	best: 0.2249283 (100)	total: 1.92s	remaining: 17.1s
150:	learn: 0.2152174	test: 0.2160859	best: 0.2160859 (150)	total: 2.88s	remaining: 16.2s
200:	learn: 0.2070330	test: 0.2079267	best: 0.2079267 (200)	total: 3.83s	remaining: 15.2s
250:	learn: 0.2000941	test: 0.2007032	best: 0.2007032 (250)	total: 5.08s	remaining: 15.2s
300:	learn: 0.1942385	test: 0.1946002	best: 0.1946002 (300)	total: 6.2s	remaining: 14.4s
350:	learn: 0.1885742	test: 0.1886768	best: 0.1886768 (350)	total: 7.2s	remaining: 13.3s
400:	learn: 0.1835729	test: 0.1833543	best: 0.1833543 (400)	total: 8.14s	remaining: 12.2s
450:	learn: 0.1790644	test: 0.1786927	best: 0.1786927 (450)	total: 9.03s	remaining: 11s
500:	learn: 0.1747245	test: 0.1742226	best: 0.1742226 (500)	total: 9.92s	remaining: 9.88s
550:	learn: 0.1703308	test: 0.1695611	best: 0.1695611 (550)	total: 10.8s	remaining: 8.81s
600:	learn: 0.1669003	test: 0.1661291	best: 0.1661291 (600)	total: 11.7s	remaining: 7.75s
650:	learn: 0.1635100	test: 0.1625513	best: 0.1625513 (650)	total: 12.5s	remaining: 6.72s
700:	learn: 0.1599347	test: 0.1589269	best: 0.1589269 (700)	total: 13.4s	remaining: 5.73s
750:	learn: 0.1564815	test: 0.1552932	best: 0.1552932 (750)	total: 14.3s	remaining: 4.74s
800:	learn: 0.1535298	test: 0.1522979	best: 0.1522979 (800)	total: 15.2s	remaining: 3.77s
850:	learn: 0.1505233	test: 0.1493083	best: 0.1493083 (850)	total: 16s	remaining: 2.81s
900:	learn: 0.1476876	test: 0.1464936	best: 0.1464936 (900)	total: 16.9s	remaining: 1.86s
950:	learn: 0.1451051	test: 0.1439260	best: 0.1439260 (950)	total: 17.8s	remaining: 919ms
999:	learn: 0.1424751	test: 0.1412611	best: 0.1412611 (999)	total: 18.7s	remaining: 0us

bestTest = 0.1412611202
bestIteration = 999

FOLD: 2
Learning rate set to 0.086301
0:	learn: 0.2579931	test: 0.2581815	best: 0.2581815 (0)	total: 18.7ms	remaining: 18.7s
50:	learn: 0.2313967	test: 0.2299273	best: 0.2299273 (50)	total: 988ms	remaining: 18.4s
100:	learn: 0.2237409	test: 0.2218827	best: 0.2218827 (100)	total: 1.92s	remaining: 17.1s
150:	learn: 0.2152174	test: 0.2134731	best: 0.2134731 (150)	total: 2.86s	remaining: 16.1s
200:	learn: 0.2070330	test: 0.2050144	best: 0.2050144 (200)	total: 3.79s	remaining: 15.1s
250:	learn: 0.2000941	test: 0.1979534	best: 0.1979534 (250)	total: 4.71s	remaining: 14.1s
300:	learn: 0.1942385	test: 0.1921641	best: 0.1921641 (300)	total: 5.62s	remaining: 13.1s
350:	learn: 0.1885742	test: 0.1865739	best: 0.1865739 (350)	total: 6.58s	remaining: 12.2s
400:	learn: 0.1835729	test: 0.1816988	best: 0.1816988 (400)	total: 7.43s	remaining: 11.1s
450:	learn: 0.1790644	test: 0.1771048	best: 0.1771048 (450)	total: 8.39s	remaining: 10.2s
500:	learn: 0.1747245	test: 0.1728148	best: 0.1728148 (500)	total: 9.32s	remaining: 9.29s
550:	learn: 0.1703308	test: 0.1684398	best: 0.1684398 (550)	total: 10.2s	remaining: 8.32s
600:	learn: 0.1669003	test: 0.1650487	best: 0.1650487 (600)	total: 11.1s	remaining: 7.34s
650:	learn: 0.1635100	test: 0.1617213	best: 0.1617213 (650)	total: 11.9s	remaining: 6.39s
700:	learn: 0.1599347	test: 0.1581612	best: 0.1581612 (700)	total: 12.8s	remaining: 5.46s
750:	learn: 0.1564815	test: 0.1546971	best: 0.1546971 (750)	total: 13.7s	remaining: 4.54s
800:	learn: 0.1535298	test: 0.1518370	best: 0.1518370 (800)	total: 14.6s	remaining: 3.62s
850:	learn: 0.1505233	test: 0.1488321	best: 0.1488321 (850)	total: 15.5s	remaining: 2.71s
900:	learn: 0.1476876	test: 0.1460584	best: 0.1460584 (900)	total: 16.3s	remaining: 1.79s
950:	learn: 0.1451051	test: 0.1435013	best: 0.1435013 (950)	total: 17.2s	remaining: 884ms
999:	learn: 0.1424751	test: 0.1408302	best: 0.1408302 (999)	total: 18.2s	remaining: 0us

bestTest = 0.1408302164
bestIteration = 999

FOLD: 3
Learning rate set to 0.086301
0:	learn: 0.2579931	test: 0.2599101	best: 0.2599101 (0)	total: 25.5ms	remaining: 25.5s
50:	learn: 0.2313967	test: 0.2335686	best: 0.2335686 (50)	total: 1.3s	remaining: 24.1s
100:	learn: 0.2237409	test: 0.2259643	best: 0.2259643 (100)	total: 2.32s	remaining: 20.7s
150:	learn: 0.2152174	test: 0.2170253	best: 0.2170253 (150)	total: 3.25s	remaining: 18.3s
200:	learn: 0.2070330	test: 0.2086020	best: 0.2086020 (200)	total: 4.17s	remaining: 16.6s
250:	learn: 0.2000941	test: 0.2015600	best: 0.2015600 (250)	total: 5.11s	remaining: 15.2s
300:	learn: 0.1942385	test: 0.1956637	best: 0.1956637 (300)	total: 6.02s	remaining: 14s
350:	learn: 0.1885742	test: 0.1899340	best: 0.1899340 (350)	total: 6.92s	remaining: 12.8s
400:	learn: 0.1835729	test: 0.1849223	best: 0.1849223 (400)	total: 7.79s	remaining: 11.6s
450:	learn: 0.1790644	test: 0.1804174	best: 0.1804174 (450)	total: 8.64s	remaining: 10.5s
500:	learn: 0.1747245	test: 0.1760315	best: 0.1760315 (500)	total: 9.57s	remaining: 9.54s
550:	learn: 0.1703308	test: 0.1716961	best: 0.1716961 (550)	total: 10.5s	remaining: 8.53s
600:	learn: 0.1669003	test: 0.1681804	best: 0.1681804 (600)	total: 11.3s	remaining: 7.51s
650:	learn: 0.1635100	test: 0.1648801	best: 0.1648801 (650)	total: 12.2s	remaining: 6.52s
700:	learn: 0.1599347	test: 0.1613348	best: 0.1613348 (700)	total: 13s	remaining: 5.57s
750:	learn: 0.1564815	test: 0.1578646	best: 0.1578646 (750)	total: 13.9s	remaining: 4.62s
800:	learn: 0.1535298	test: 0.1548378	best: 0.1548378 (800)	total: 14.8s	remaining: 3.68s
850:	learn: 0.1505233	test: 0.1518458	best: 0.1518458 (850)	total: 15.7s	remaining: 2.75s
900:	learn: 0.1476876	test: 0.1489822	best: 0.1489822 (900)	total: 16.6s	remaining: 1.82s
950:	learn: 0.1451051	test: 0.1463580	best: 0.1463580 (950)	total: 17.5s	remaining: 900ms
999:	learn: 0.1424751	test: 0.1436760	best: 0.1436760 (999)	total: 18.3s	remaining: 0us

bestTest = 0.1436760196
bestIteration = 999

FOLD: 4
Learning rate set to 0.08333
0:	learn: 0.2584157	test: 0.2568458	best: 0.2568458 (0)	total: 24.3ms	remaining: 24.2s
50:	learn: 0.2310747	test: 0.2364251	best: 0.2364251 (50)	total: 910ms	remaining: 16.9s
100:	learn: 0.2223143	test: 0.2342897	best: 0.2342897 (100)	total: 1.77s	remaining: 15.8s
150:	learn: 0.2127078	test: 0.2330257	best: 0.2330257 (150)	total: 2.62s	remaining: 14.7s
200:	learn: 0.2033503	test: 0.2325439	best: 0.2324522 (191)	total: 3.43s	remaining: 13.6s
250:	learn: 0.1956771	test: 0.2325085	best: 0.2323786 (225)	total: 4.26s	remaining: 12.7s
300:	learn: 0.1890850	test: 0.2325189	best: 0.2323786 (225)	total: 5.07s	remaining: 11.8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.2323785873
bestIteration = 225

Shrink model to first 226 iterations.
0.1966141963746153

In [10]:
id = pandas.read_csv('/kaggle/input/equity-post-HCT-survival-predictions/test.csv')['ID']
test_predictions = (cat_pre_test)
#((RandomF_pre_test/Fold)+(LGBM_pre_test/Fold)+(xgb_pre_test/Fold)+(cat_pre_test/Fold))/4
#model.predict(new_test_data)
#((RandomF_pre_test/10)+(LGBM_pre_test/5)+(xgb_pre_test/5)+(cat_pre_test/5))/4
test_predictions

array([0.33814363, 0.86413352, 0.36832339])

In [11]:
submission = pandas.DataFrame({
    'ID': id.values,
    'prediction': test_predictions,
})
submission

      ID  prediction
0  28800    0.338144
1  28801    0.864134
2  28802    0.368323

In [12]:
submission.to_csv('submission.csv', index = False)